# Base image
FROM {{ base_image }}

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install dependencies (if applicable)
RUN {{ command_to_install_dependencies}}

# Expose any necessary ports
EXPOSE {{ port_number }}

# Set any required environment variables
ENV <key>=<value>

# Run the application or command
CMD ["{{ dockerfile_command_to_run }} "]
